### ISSUE TITLE
Re-create TCGA runs for 3.0 

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1276]
Pre-conditions: 
- [x] Fixed Color Scale for categorical data (depends on #1275)
- [x] Imported new color scale according to (depends on #1277 )
- [x] Apply new color scales #1299

**Comment by sgratzl** [comment]
some one has to tell me what color + brightness I should use for which data type:
- mRNA
- mRNAseq
- microRNA
- microRNAseq
- methylation
- RPPA
- copyNumber
- mutation
- clinical

**Comment by ngehlenborg** [comment]
Can we make this similar to what we had in good old days (see http://compbio.med.harvard.edu/tcga/stratomex)?

Please use the same color for XXX and XXXseq.

**Comment by ngehlenborg** [comment]
Colors in current sample set are fine as far as I can tell.

**Comment by alexsb** [comment]
Did someone fix #1299 because it looks like it's fixed - I closed it. Then this is good to go.

**Comment by sgratzl** [comment]
- what will be the target folder?
  do we still host it at harvard, at icg graz, oder at our caleydo vm?
- as I assume that @alexsb is doing the release as well as the webstart version, can I have a jnlp template

**Comment by mstreit** [comment]
We will host it at our Caleydo VM server.
I've updated the JNLP template file. However, it needs to be tested with an export.

**Comment by mstreit** [comment]
The caleydo VM can be reached via http://dev.caleydo.org/.
However, this is not a nice URL for hosting our data packages. I suggest to let Mark configure "data.caleydo.org" and make it point to "dev.caleydo.org/data"

**Comment by ngehlenborg** [comment]
At some point we should consider finding a location that has a better connection for downloads. Downloading the latest builds from the VM in Graz takes more than 5 minutes for me.

**Comment by sgratzl** [comment]
maybe something like Amazon S3

**Comment by mstreit** [comment]
@ngehlenborg How big was the file that took 5 mins to load?

**Comment by ngehlenborg** [comment]
137 MB

**Comment by mstreit** [comment]
the 77MB CCLE project file needs about 10 second here at JKU

**Comment by alexsb** [comment]
The ccle file was fast enough for me too.

Concerning release: I don't have to do it - I think my build still includes a lot of unnecessary stuff. The latest builds have 130 mb, but should have less than the old ones.

**Comment by alexsb** [comment]
@mstreit provides jnlp templates

**Comment by alexsb** [comment]
Needs to be re-run again. Also, sample gbm project needs to be replaced.

**Comment by sgratzl** [comment]
will create all 2013 ones after the release to have a stable state

**Comment by sgratzl** [comment]
2013_01_16, 2013_02_22, 2013_03_26, 2013_04_21 and 2013_05_23 are available now
